CREATE TABLE `ORDER`
(
    `ID`               VARCHAR(38) PRIMARY KEY,
    `PARKING_LOT_NAME` VARCHAR(255) NOT NULL,
    `CARD_NUMBER`      VARCHAR(255) NOT NULL,
    `CREATE_TIME`      DATETIME     NOT NULL,
    `LEAVE_TIME`       DATETIME,
    `PARKING_LOT_ID`   VARCHAR(38)  NOT NULL
);